# Constants

INTRODUCTION = """Welcome to Midnight Rider

WE'VE STOLEN A CAR. WE NEED TO GET IT HOME.
THE CAR IS SPECIAL.

THAT'S THE WHY THE GOVERNMENT WANTS IT.

WE CAN't LET THEM HAVE IT.

ONE GOAL: SURVIVAL.... AND THE CAR
REACH THE SAFEHOUSE BEFORE THE MAN
GON GETCHU.
"""

CHOICES = """
    --- Your Choices ---
    A. Eat food
    B. Travel moderately
    C. Speed ahead at full speed
    D. Stop to refuel
    E. Current Status
    Q. Quit the game
    ---
"""

REFUEL = """-------You filled the fuel tank.
-------The agents got closer...
"""

EAT_FOOD = """-------Mmmmm. Your hunger is sated
"""

NO_FOOD = """--------You have no food.
"""

SEVERE_HUNGER ="""**********Your stomach rumbles You need to eat something quick.
"""
HUNGER = """**********Your hunger is small but manageable.
"""

ENDGAME_TEXT = [
    """The game has ended. Thanks for playing!""",     # Quit the game
    """\n\nTHE AGENTS HAVE CLOSED IN ON YOU.
THERE ARE AT LEAST AT LEAST CARS SURROUNDING YOU.
THE LEAD CAR BUMPS YOUR PASSENGER SIDE.
YOU MANAGE TO CORRECT YOUR STEERING
TO KEEP YOU FROM CRASHING.

YOU DIDN'T SEE THE AGENT'S CAR RIGHT BESIDE YOU.
THAT DRIVER BUMPS YOUR CAR.
AND THAT'S It.

YOU SPIN UNCONTROLLABLY.
YOUR CAR FLIPS OVER AT LEAST TWO TIMES.
OR MORE... YOU SEEM TO HAVE LOST COUNT.

SIRENS.

"ARE THEY ALIVE?" THEY SAY AS YOU HEAR
FOOTSTEPS COMING CLOSER.
"DOESN'T MATTER, ALL WE WANTED WAS THE CAR."
YOU SEE A DOG SLOWLY STEP OUT OF THE OVERTURNED CAR.

"YOU WILL NEVER STOP THE REVOLUTION!
THE DOG SEEMS TO SAY TO THE AGENTS.

IT WAS IN THE CAR THE WHOLE TIME.
YOU DRIFT OFF INTO UNCONSCIOUSNESS...

---GAME OVER---
\n""",      # LOSE - Agents have caught up
    """YOUR CAR SPUTTERS AND SEEMS TO LET OUT
A BIG SIGH. THERE'S NO MORE FUEL LEFT.

THE AGENTS SURROUND YOU AND STEP OUT OF THEIR CARS. 
THE LEAD AGENT RIPS THE DOOR OPEN AND THROWS YOU OUT OF YOUR CAR.

"WE FINALLY GOT IT."

YOU FAILED.

---GAME OVER---""",     # LOSE - Run out of fuel
    """\n\nYOUR STOMACH IS EMPTY.
WHO KNEW THAT WHAT THE DOCTOR SAID WAS TRUE,
THAT HUMAN/ROBOT HYBRIDS WOULD NEED
FOOD TO SUSTAIN THEMSELVES.
YOUR ROBOT SYSTEMS START TO SHUT DOWN.
YOUR HUMAN EYES CLOSE.
THE LAST THING THAT YOU HEAR ARE SIRENS.
THEY GOTCHU. THEY GOT THE CAR.
WE FAILED...

----GAME OVER----
""",     # LOSE - Starvation

]